## Target platform
platform :ios, '9.0'

## External source
source 'https://github.com/CocoaPods/Specs.git'

## Use frameworks
use_frameworks!

target 'ArubaCommons_Example' do
  pod 'ArubaCommons', :path => '../'

  target 'ArubaCommons_Tests' do
    inherit! :search_paths

    
  end
end
